### ISSUE TITLE
VS errors

### ISSUE THREAD

**Issue by Coolejungee** [emlai/zenith#1]
Greetings Emil

I downloaded your roguelike project on github a couple days ago. I usually use Visual Studio for most of my programming, so I tried building your project with it. I reckoned that it would work since VS has Cmake support. But since I'm not too familiar with C++ I encountered lnk 2005 errors whenever I thought I solved another error.  These errors are related to mapkey, savekeymap, etc which are used in Component.cpp, Controller.cpp and Controller.h

If you have the time would you be so kind to take a look at it and point me in the right direction?
I must say I have learned a bit just from trying to correct errors altough I would love to see the actual game.

Thanks in advance

Zenith-Master file can be found below.
https://drive.google.com/file/d/1SQG_LAVDxg39xAkDX25hlEx-9WvekMVZ/view

**Comment by emillaine** [comment]
Hey!

Glad you're interested in the project.

I updated the README with build instructions for Windows. Hope they'll help.

So in Command Prompt in the project root directory you can run `cmake . -DSDL2_PATH="C:\path\to\SDL2-2.0.9"`  to generate a Visual Studio solution. Then you can open the solution (for me it's named `zenith.sln`) and build the project in the normal Visual Studio way. You may need to copy SDL2.dll to the project root directory though to run the game.

Let me know if this works for you!

**Comment by Coolejungee** [comment]
Hi Emil

Thank you for the quick response.

I followed the steps you provided and the project builds in VS without errors.

When I try to run the .EXE file from the root directory, I get prompted with the error "(0xc000007b)" This is probably related to the diffirence in WIN32, x64 or x86. 

Do you have an idea on how to change to x64 in cmake, which I assume causes this error.

Cheers

**Comment by emillaine** [comment]
I got the 0xc000007b error too and it turned out I had copied the 64-bit SDL2.dll instead of the 32-bit one, and my build was 32-bit. So check that you use the correct SDL2.dll.

Also you can change the build to be 64-bit with e.g.:

```
cmake -DCMAKE_GENERATOR_PLATFORM=x64 .
```

(from https://stackoverflow.com/q/28350214/3425536)

**Comment by Coolejungee** [comment]
Thank your very much for your help and time. The project runs smoothly now.

**Comment by emillaine** [comment]
Nice!
