### ISSUE TITLE
Build error on Crystal 0.17-3

### ISSUE THREAD

**Issue by puppetpies** [emlai/zenith#2]
Don't know if you aware of this but this is error i'm currently seeing.

[brian@orville zenith]$ make
Error in ./src/messages.cr:43: macro didn't expand to a valid program, it expanded to:

================================================================================
--------------------------------------------------------------------------------
  1.     
  2.       
  3. 
  4.       def is_new = true
  5.         @is_new = true
  6.       end
  7.     
  8.   
--------------------------------------------------------------------------------
Syntax error in expanded macro: getter:4: unexpected token: =

      def is_new = true
                 ^

================================================================================

  getter is_new = true
  ^~~~~~

Makefile:2: recipe for target 'build' failed
make: *** [build] Error 1
[brian@orville zenith]$ crystal version
Crystal 0.17.3 [c8dd01f] (Fri May 20 17:02:56 UTC 2016)

**Comment by puppetpies** [comment]
Simple one.

--- a/src/messages.cr
+++ b/src/messages.cr
@@ -40,11 +40,13 @@ end
 
 class Message
   property text : String
-  getter is_new = true
-  getter repetition_count = 1
+  getter is_new #= true
+  getter repetition_count # = 1
 
   def initialize(text)
     @text = text
+    @is_new = true
+    @repetition_count = 1
   end

**Comment by emlai** [comment]
Thanks! What version of Crystal are you using?

My guess is that `getter is_new = true` doesn't work on older versions of Crystal. I have 0.17.4 and it works fine.

**Comment by puppetpies** [comment]
I'm on 0.17.3 new feature i'll have a look.

**Comment by puppetpies** [comment]
Actually yes as of 0.17.4

The property, getter and setter macros now also accept assignments (property x = 0)

**Comment by asterite** [comment]
I don't think it's worth keeping backwards compatibility with older crystal versions. Crystal 0.17.3 has many bugs, Crystal 0.17.4 fixes them.

**Comment by asterite** [comment]
And it's really easy to upgrade from 0.17.3 to 0.17.4 :-)

**Comment by emlai** [comment]
Yeah, probably not. But 0.16.0 is still the only version on Homebrew, and people who are not actively using Crystal but want to quickly compile this project to try it out can do so more easily now.

**Comment by asterite** [comment]
[0.17.4 is on homebrew](https://github.com/Homebrew/homebrew-core/pull/1455), did you do `brew update`?

**Comment by emlai** [comment]
Ohh, looks like I haven't done that in a while. There it is, thanks!
